version: "2"
services:
    mysql:
         image: mysql:latest
         environment:
            - MYSQL_ROOT_PASSWORD=passwd
            - MYSQL_PASSWORD=passwd 
            - MYSQL_USER=root
            - MYSQL_DATABASE=springboot_mysql_example
         ports:
           - 3306:3306
    web:
        image: ahmedibrahim9/java-maven-mysql:master-3b922c1
        depends_on:
            - mysql
        ports:
            - 8080:8080
        environment:
            - DATABASE_HOST=mysql
            - DATABASE_USER=root
            - DATABASE_PASSWORD=passwd
            - DATABASE_NAME=springboot_mysql_example
            - DATABASE_PORT=3306
