version: "2"
services:
    mysql:
         image: mysql:latest
         environment:
                    - MYSQL_ROOT_PASSWORD=passwd
                    - MYSQL_PASSWORD=passwd 
                    - MYSQL_USER=ahmed
                    - MYSQL_DATABASE=mysql
        ports:
           - 3306:3306
    web:
        image: myimage
        depends_on:
            - mysql
        ports:
            - 8080:8080
        environment:
            - DATABASE_HOST=mysql
            - DATABASE_USER=ahmed
            - DATABASE_PASSWORD=passwd
            - DATABASE_NAME=mysql
            - DATABASE_PORT=3306
