apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: app
        image: mysql:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: passwd
        - name: MYSQL_PASSWORD
          value: passwd
        - name: MYSQL_USER
          value: ahmed
        - name: MYSQL_DATABASE
          value: mysql        
        ports:
        - containerPort: 3306
          protocol: TCP